### ISSUE TITLE
Limit size of cache

### ISSUE THREAD

**Issue by trycoon** [arthurfiorette/axios-cache-interceptor#539] opened 2023-05-22 13:06 UTC
Except TTL-time, it would be very useful to be able to limit the size of the cache!
If you request binary data from Axios, like images, the response could be several hundred kilobytes big, handling lots of request for different images may eat up lot of the available memory for Node.js and eventually make it crash with Out Of Memory (long before TTL has been reacted).  A limit of the cache size, like max number of entries or max bytes allowed would really help this scenario, and cache entries could be evicted based upon a Least-Recent-Usage principle.

For Redis this could be set on the server, for in-Memory a store based upon https://www.npmjs.com/package/weak-lru-cache could be used.

**Comment by arthurfiorette** [comment] 2023-05-25 16:05
Hey @trycoon, Guessing the size of variables in nodejs cannot be done and only expensive "extimatives" can be done, however a `maxEntries` option would be an awesome feature!

LRU will be an expensive implementation as we would need to store timestamps on every access, but a smart FIFO could also be used to minimize this problem.

**Comment by arthurfiorette** [comment] 2023-05-25 16:11
Just to mark something I've never done before and now I am feeling very proud of myself:

![Imagem do WhatsApp de 2023-05-25 à(s) 13 02 35](https://github.com/arthurfiorette/axios-cache-interceptor/assets/47537704/fb4aac3f-01e6-47b9-9992-62e231dbe78e)

My first time getting a segfault on **NodeJS**. _(While writing a test for this PR, could not reproduce it)_

**Comment by arthurfiorette** [comment] 2023-05-25 16:17
Closed as implemented on ebd400b.

**Closed by arthurfiorette** 2023-05-25 16:17 UTC

**Comment by trycoon** [comment] 2023-05-27 21:09
Thanks, a maxEntries feature is better than none. In cases when object size is always the same, it offers excellent protection. In cases when object size could differ alot, you may run out of heap space after just ten entries, but in that case you could always write your own cache implementation. After all, its very pluggable. :-)
