### ISSUE TITLE
Feature request: Invalidate all 

### ISSUE THREAD

**Issue by aaronfultonnz** [arthurfiorette/axios-cache-interceptor#799] opened 2024-03-01 03:57 UTC
I'd like a feature to "invalidate all". I make heavy use of caching (front-end and backend) in my application and sometimes we need to "clear all caches". At the moment there is no easy way to do this using axios-cache-iterceptor other than keeping track of all cache keys and learning them out one by one.

let me know if you'd like me to submit a PR for this.

**Comment by arthurfiorette** [comment] 2024-03-01 04:37
You can implement a custom storage for this, this is out of scope because it will be an "storage" feature that won't be used by the internals of the interceptor, which is what the storage was designed for.

If you are using memory storage, just reseting the internal data property is enough. If you are using web storages, probably just [getting all local/session storage keys](https://stackoverflow.com/questions/8419354/get-html5-localstorage-keys) and deleting one by one is the solution to go for.

Let me know if you are having any more problems :)

**Closed by arthurfiorette** 2024-03-01 04:37 UTC
