### ISSUE TITLE
bug: "Cannot read properties of undefined (reading 'id')" when reading cached response

### ISSUE THREAD

**Issue by thutter** [arthurfiorette/axios-cache-interceptor#524] opened 2023-04-05 16:35 UTC
### Describe the bug

I created the cache with the default memory storage. I'm caching a response successfully. Trying to read the cached reponse causes `Cannot read properties of undefined (reading 'id')`. I'm using Next.js and do the request server side. I'm transforming the response. I tried to use the default memory storage with copy set to true and false.

### To Reproduce

1. Create instance 
```
const managementApi = setupCache(
  axios.create({
    baseURL: BASE_URL,
  }),
  {
    storage: buildMemoryStorage(true),
    debug: console.log,
  },
)
```

2. Do the request. The response has the `Cache-Control: no-cache` header, so I set interpretHeader to false.
```
const getUserDetails = (id: number) =>
  managementApi.get<UserDetails, CacheAxiosResponse<Project>>(
    `${BASE_URL}/${id}`,
    {
      transformResponse: transformProjectToUser,
      cache: {
        interpretHeader: false,
      },
    },
  )
  
const transformProjectToUser = (projectJson: string): UserDetails => {
  const project = JSON.parse(projectJson)
  return {...}
}

# this is called in getServerSideProps of a page
const user = await getUserDetails(23777)
```

3. Reloading a page that does the request server side several times causes this issue.
```
{
  id: '1029618082',
  msg: 'Sending request, waiting for response',
  data: { overrideCache: false, state: 'empty' }
}
{
  id: '1029618082',
  msg: 'Useful response configuration found',
  data: {
    cacheConfig: {
      update: {},
      ttl: 300000,
      methods: [Array],
      cachePredicate: [Object],
      etag: true,
      modifiedSince: false,
      interpretHeader: false,
      cacheTakeover: true,
      staleIfError: true,
      override: false
    },
    cacheResponse: {
      data: [Object],
      status: 200,
      statusText: 'OK',
      headers: [AxiosHeaders]
    }
  }
}
{
  id: '1029618082',
  msg: 'Found waiting deferred(s) and resolved them'
}
{
  id: '1029618082',
  msg: 'Response cached',
  data: {
    cache: {
      state: 'cached',
      ttl: 300000,
      createdAt: 1680712304783,
      data: [Object]
    },
    response: {
      status: 200,
      statusText: 'OK',
      headers: [AxiosHeaders],
      config: [Object],
      request: [ClientRequest],
      data: [Object],
      id: '1029618082',
      cached: false
    }
  }
}
{
  id: '1029618082',
  msg: 'Sending request, waiting for response',
  data: { overrideCache: false, state: 'empty' }
}
{
  id: '1029618082',
  msg: 'Useful response configuration found',
  data: {
    cacheConfig: {
      update: {},
      ttl: 300000,
      methods: [Array],
      cachePredicate: [Object],
      etag: true,
      modifiedSince: false,
      interpretHeader: false,
      cacheTakeover: true,
      staleIfError: true,
      override: false
    },
    cacheResponse: {
      data: [Object],
      status: 200,
      statusText: 'OK',
      headers: [AxiosHeaders]
    }
  }
}
{
  id: '1029618082',
  msg: 'Found waiting deferred(s) and resolved them'
}
{
  id: '1029618082',
  msg: 'Response cached',
  data: {
    cache: {
      state: 'cached',
      ttl: 300000,
      createdAt: 1680712344683,
      data: [Object]
    },
    response: {
      status: 200,
      statusText: 'OK',
      headers: [AxiosHeaders],
      config: [Object],
      request: [ClientRequest],
      data: [Object],
      id: '1029618082',
      cached: false
    }
  }
}
{ id: '1029618082', msg: 'Returning cached response' }
[18:32:27.255] ERROR (33010): Cannot read properties of undefined (reading 'id')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'id')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'id')
              at r (file:///Users/user/Work/ekd/customer-portal-frontend-next/node_modules/axios-cache-interceptor/dev/index.mjs:1:7150)
              at async getServerSideProps (webpack-internal:///./src/pages/home/dashboard.tsx:296:30)
    }
```

### Expected behavior

Cached response is available.

### Additional context

- Axios: `^1.3.4`
- Axios Cache Interceptor: `^1.0.1`
- What storage is being used: `Memory Storage`
- Node Version: `v18.12.1`
- Browser (if applicable): `run serverside`

**Comment by arthurfiorette** [comment] 2023-04-09 15:27
Hey @thutter, just did a test (a2dbb5f) and it seems to be working. About the `Cannot read properties of undefined (reading 'id')` error, the next version will introduce a catch clause and a debug statement (360ba57) to provide more useful information. 

`transformResponse` just changes the server's data, it cannot change the axios response object that axios-cache-interceptor works with, and we just store `response.data`, no iteractions with it are done. You are probably throwing an error inside your `transformProjectToUser` function.

As you did not provided an reproducible example and I couldn't reproduce your problem, I'll close this issue, but feel free to reopen it :)

**Closed by arthurfiorette** 2023-04-09 15:27 UTC
Labels: bug

**Comment by pilartomas** [comment] 2023-04-24 06:53
I am experiencing the same problem without the transform function, with default cache configuration.

The trigger in my code seems to be the `timeout` of the request. Specifically, timeout of 10 milliseconds in my unit tests causes the TypeError. I've lowered the timeout to 1ms which seems to bypass the issue.
